# Generated by Django 5.2 on 2025-05-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Jugador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('partidos_ganados', models.PositiveIntegerField()),
                ('partidos_perdidos', models.PositiveIntegerField()),
                ('jugador', models.ManyToManyField(to='Jugador.jugador')),
            ],
        ),
    ]
