# Generated by Django 5.2 on 2025-05-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Autor', '0001_initial'),
        ('Libreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('anio', models.PositiveIntegerField()),
                ('autores', models.ManyToManyField(related_name='libros', to='Autor.autor')),
                ('librerias', models.ManyToManyField(related_name='libros', to='Libreria.libreria')),
            ],
        ),
    ]
