# Generated by Django 5.2 on 2025-05-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('anio', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=100)),
                ('paginas', models.CharField(max_length=100)),
                ('investigador', models.ManyToManyField(related_name='libro', to='investigador.investigador')),
            ],
        ),
    ]
