# Generated by Django 5.2 on 2025-05-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0001_initial'),
        ('investigador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('anio', models.CharField(max_length=4)),
                ('ISBN', models.CharField(max_length=20, unique=True)),
                ('paginas', models.CharField(max_length=4)),
                ('investigadores', models.ManyToManyField(related_name='libros', to='investigador.investigador')),
            ],
        ),
        migrations.DeleteModel(
            name='Libros',
        ),
    ]
