# Generated by Django 5.2 on 2025-05-27 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0002_libro_delete_libros'),
        ('investigador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('anio', models.CharField(max_length=4)),
                ('ISBN', models.CharField(max_length=20, unique=True)),
                ('paginas', models.CharField(max_length=4)),
                ('investigadores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigador.investigador')),
            ],
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
    ]
